# Generated by Django 5.1.6 on 2025-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_tbl_district_delete_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Administrator_name', models.CharField(max_length=50)),
                ('Administrator_email', models.CharField(max_length=50)),
                ('Administrator_passwordt', models.CharField(max_length=50)),
            ],
        ),
    ]
