# Generated by Django 5.1.6 on 2025-02-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_tbl_userregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_UserRegistration',
            new_name='tbl_Administrator',
        ),
        migrations.RenameField(
            model_name='tbl_administrator',
            old_name='Administrator_passwordt',
            new_name='Administrator_password',
        ),
    ]
