# Generated by Django 5.1.6 on 2025-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_rename_tbl_userregistration_tbl_administrator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
