# Generated by Django 5.1.6 on 2025-03-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0005_tbl_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_educationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_language',
        ),
        migrations.AddField(
            model_name='tbl_course',
            name='educationtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_educationtype'),
        ),
    ]
