# Generated by Django 5.1.6 on 2025-02-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_delete_tbl_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_UserRegistration',
        ),
    ]
