# Generated by Django 5.1.6 on 2025-02-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
        ('User', '0007_remove_tbl_changepassword_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_UserRegistration',
        ),
    ]
