# Generated by Django 5.1.6 on 2025-03-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=50)),
                ('index_email', models.CharField(max_length=50)),
                ('index_message', models.CharField(max_length=50)),
            ],
        ),
    ]
