# Generated by Django 5.1.6 on 2025-03-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_index',
        ),
    ]
