# Generated by Django 5.1.6 on 2025-03-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_delete_tbl_index'),
        ('User', '0013_remove_tbl_certificate_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_UserRegistration',
        ),
    ]
