# Generated by Django 5.1.6 on 2025-02-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education_Institution', models.CharField(max_length=50)),
                ('Education_FieldOfstudy', models.CharField(max_length=50)),
                ('Education_Year', models.CharField(max_length=50)),
                ('Education_Graduation', models.CharField(max_length=50)),
                ('Education_StartDate', models.CharField(max_length=50)),
                ('Education_EndDate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience_Jobtitle', models.CharField(max_length=50)),
                ('Experience_Companyname', models.CharField(max_length=50)),
                ('Experience_Experience', models.CharField(max_length=50)),
                ('Experience_Startdate', models.CharField(max_length=50)),
                ('Experience_Enddate', models.CharField(max_length=50)),
                ('Experience_Description', models.CharField(max_length=50)),
            ],
        ),
    ]
