# Generated by Django 5.1.6 on 2025-02-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=50)),
                ('certificate_upload', models.FileField(upload_to='Assets/User/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50)),
                ('language_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=50)),
                ('Project_Details', models.CharField(max_length=50)),
                ('Project_Link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=50)),
                ('reference_email', models.CharField(max_length=50)),
                ('reference_contact', models.CharField(max_length=50)),
                ('reference_relation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
    ]
