# Generated by Django 5.1.6 on 2025-02-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_certificate_tbl_hobbies_tbl_language_tbl_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_certificate',
        ),
        migrations.DeleteModel(
            name='tbl_Education',
        ),
        migrations.DeleteModel(
            name='tbl_Experience',
        ),
        migrations.DeleteModel(
            name='tbl_hobbies',
        ),
        migrations.DeleteModel(
            name='tbl_language',
        ),
        migrations.DeleteModel(
            name='tbl_Project',
        ),
        migrations.DeleteModel(
            name='tbl_reference',
        ),
        migrations.DeleteModel(
            name='tbl_skill',
        ),
    ]
