# Generated by Django 5.1.6 on 2025-02-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0005_initial'),
        ('User', '0005_delete_tbl_certificate_delete_tbl_changepassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=50)),
                ('certificate_upload', models.FileField(upload_to='Assets/User/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Changepassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Changepassword_oldpassword', models.CharField(max_length=50)),
                ('Changepassword_newpasword', models.CharField(max_length=50)),
                ('Changepassword_confirmpassword', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Editprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Editprofile_name', models.CharField(max_length=50)),
                ('Editprofile_email', models.CharField(max_length=50)),
                ('Editprofile_contact', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education_Institution', models.CharField(max_length=50)),
                ('Education_FieldOfstudy', models.CharField(max_length=50)),
                ('Education_Year', models.CharField(max_length=50)),
                ('Education_Graduation', models.CharField(max_length=50)),
                ('Education_StartDate', models.CharField(max_length=50)),
                ('Education_EndDate', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience_Jobtitle', models.CharField(max_length=50)),
                ('Experience_Companyname', models.CharField(max_length=50)),
                ('Experience_Experience', models.CharField(max_length=50)),
                ('Experience_Startdate', models.CharField(max_length=50)),
                ('Experience_Enddate', models.CharField(max_length=50)),
                ('Experience_Description', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50)),
                ('language_level', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Myprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Myprofile_photo', models.FileField(upload_to='Assets/User/')),
                ('Myprofile_name', models.CharField(max_length=50)),
                ('Myprofile_email', models.CharField(max_length=50)),
                ('Myprofile_contact', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=50)),
                ('Project_Details', models.CharField(max_length=50)),
                ('Project_Link', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=50)),
                ('reference_email', models.CharField(max_length=50)),
                ('reference_contact', models.CharField(max_length=50)),
                ('reference_relation', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
    ]
