# Generated by Django 5.1.6 on 2025-03-02 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_initial'),
        ('User', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_name', models.CharField(max_length=50)),
                ('cv_email', models.CharField(max_length=50)),
                ('cv_contact', models.CharField(max_length=50)),
                ('cv_address', models.CharField(max_length=50)),
                ('cv_education', models.CharField(max_length=50)),
                ('cv_experience', models.CharField(max_length=50)),
                ('cv_skill', models.CharField(max_length=50)),
                ('cv_hobbies', models.CharField(max_length=50)),
                ('cv_reference', models.CharField(max_length=50)),
                ('cv_language', models.CharField(max_length=50)),
                ('cv_project', models.CharField(max_length=50)),
                ('cv_certificate', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
    ]
