# Generated by Django 5.1.6 on 2025-03-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_initial'),
        ('User', '0009_tbl_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
    ]
