# Generated by Django 5.1.6 on 2025-03-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_tbl_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_cv',
        ),
    ]
