# Generated by Django 5.1.6 on 2025-03-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_index',
        ),
    ]
