# Generated by Django 5.1.6 on 2025-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_delete_tbl_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_name', models.CharField(max_length=50)),
                ('Feedback_email', models.CharField(max_length=50)),
                ('Feedback_message', models.CharField(max_length=50)),
            ],
        ),
    ]
