# Generated by Django 5.1.6 on 2025-03-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_about',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_certificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_changepassword',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_cv',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_editprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_experience',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_Feedback',
        ),
        migrations.RemoveField(
            model_name='tbl_hobbies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_language',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_myprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_reference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_skill',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_about',
        ),
        migrations.DeleteModel(
            name='tbl_certificate',
        ),
        migrations.DeleteModel(
            name='tbl_Changepassword',
        ),
        migrations.DeleteModel(
            name='tbl_cv',
        ),
        migrations.DeleteModel(
            name='tbl_Editprofile',
        ),
        migrations.DeleteModel(
            name='tbl_Education',
        ),
        migrations.DeleteModel(
            name='tbl_Experience',
        ),
        migrations.DeleteModel(
            name='tbl_hobbies',
        ),
        migrations.DeleteModel(
            name='tbl_language',
        ),
        migrations.DeleteModel(
            name='tbl_Myprofile',
        ),
        migrations.DeleteModel(
            name='tbl_Project',
        ),
        migrations.DeleteModel(
            name='tbl_reference',
        ),
        migrations.DeleteModel(
            name='tbl_skill',
        ),
    ]
