# Generated by Django 5.1.6 on 2025-03-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_skill',
        ),
    ]
