# Generated by Django 5.1.6 on 2025-03-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_skill',
        ),
    ]
