# Generated by Django 5.1.6 on 2025-03-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_tbl_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Education',
        ),
    ]
