# Generated by Django 5.1.6 on 2025-02-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login_email', models.CharField(max_length=50)),
                ('Login_password', models.CharField(max_length=50)),
            ],
        ),
    ]
