# Generated by Django 5.1.6 on 2025-02-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Login',
        ),
        migrations.RemoveField(
            model_name='tbl_userregistration',
            name='UserRegistration_address',
        ),
        migrations.RemoveField(
            model_name='tbl_userregistration',
            name='UserRegistration_gender',
        ),
        migrations.RemoveField(
            model_name='tbl_userregistration',
            name='UserRegistration_photo',
        ),
    ]
