from django.contrib import admin
from django.urls import path
from User import views
app_name="User"
urlpatterns = [
    path("Homepage/",views.Homepage,name="Homepage"),
    path("Education/",views.Education,name="Education"),
    path("about/",views.about,name="about"),
    path("Experience/",views.Experience,name="Experience"),
    path("Project/",views.Project,name="Project"),
    path("Language/",views.Language,name="Language"),
    path("Hobbies/",views.Hobbies,name="Hobbies"),
    path("skill/",views.skill,name="skill"),
    path("ajaxcourse/",views.ajaxcourse,name="ajaxcourse"),
    path("Reference/",views.Reference,name="Reference"),
    path("Certificate/",views.Certificate,name="Certificate"),
    path("Myprofile/",views.Myprofile,name="Myprofile"),
    path("Changepassword/",views.Changepassword,name="Changepassword"),
    path("Editprofile/",views.Editprofile,name="Editprofile"),
    path("R1/",views.R1,name="R1"),
    path("R2/",views.R2,name="R2"),
    path("R3/",views.R3,name="R3"),
    path("R4/",views.R4,name="R4"),
    path("R5/",views.R5,name="R5"),
    path("Choose/",views.Choose,name="Choose"),
    path("T1/",views.T1,name="T1"),
    path("cv/",views.cv,name="cv"),
    path("C1/",views.C1,name="C1"),
    path("C2/",views.C2,name="C2"),
    path("C3/",views.C3,name="C3"),
    path("C4/",views.C4,name="C4"),
    path("C5/",views.C5,name="C5"),
    path("Choose1/",views.Choose1,name="Choose1"),
    path("Feedback/",views.Feedback,name="Feedback"),
    path("Customization/",views.Customization,name="Customization"),
    path("edit_about/<int:id>",views.edit_about,name="edit_about"),
    path("deleteabout/<int:id>",views.deleteabout,name="deleteabout"),
    path("deleteeducation/<int:id>",views.deleteeducation,name="deleteeducation"),
    path("delete_experience/<int:id>",views.delete_experience,name="delete_experience"),
    path("delete_skill/<int:id>",views.delete_skill,name="delete_skill"),
    path("delete_hobby/<int:id>",views.delete_hobby,name="delete_hobby"),
    path("delete_reference/<int:id>",views.delete_reference,name="delete_reference"),
    path("delete_language/<int:id>",views.delete_language,name="delete_language"),
    path("delete_project/<int:id>",views.delete_project,name="delete_project"),
    path("delete_certificate/<int:id>",views.delete_certificate,name="delete_certificate"),
]